name: Build Firmware

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.1
    steps:
      - uses: actions/checkout@v3
      - name: Build and test with idf.py
        shell: bash
        run: |
          . "$IDF_PATH/export.sh"
          idf.py build && idf.py test
