name: Build Firmware

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.1
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        shell: bash
        run: |
          . "$IDF_PATH/export.sh"
          idf.py build

      - name: Build unit tests
        shell: bash
        run: |
          . "$IDF_PATH/export.sh"
          idf.py -C tests/hardware build
